"""
patch_phase3_params.py
======================
Phase 3 — Parameter integration: verdrahtet alle Screen-Parameter-Widgets
mit den entsprechenden TNC-Befehlen.

Abgedeckte Modi:
  PACTOR   — MYPTCALL (le_myptcall)
  AMTOR    — MYSELCAL, MYALTCAL, MYIDENT (le_myselcal, le_myaltcal, le_myident)
  Morse    — MSPEED (sb_mspeed), MWEIGHT (sb_mweight), MID (sb_mid), LOCK (btn_lock)
  Morse    — Toggle: EAS (btn_eas), WORDOUT (btn_wordout), MOPTT (btn_moptt)
  NAVTEX   — NAVMSG checkboxes (_msg_checks), NAVSTN (le_navstn)
  PACTOR   — Toggle: PT200 (btn_pt200), PTHUFF (btn_pthuff), PTROUND (btn_ptround), EAS (btn_eas)
  AMTOR    — Toggle: RXREV (btn_rxrev), TXREV (btn_txrev), RFEC (btn_rfec),
                     SRXALL (btn_srxall), EAS (btn_eas)
  Baudot/ASCII — Toggle: RXREV (btn_rxrev), TXREV (btn_txrev), EAS (btn_eas),
                          WIDESHFT (btn_wideshft)

Alle Verdrahtungen folgen demselben Guard:
  if not self._serial.is_connected or not self._serial.is_host_mode: return

Aufruf vom Repo-Root:
    python patch_phase3_params.py
"""

from pathlib import Path

TARGET = Path("src/pk232py/ui/main_window.py")

PATCHES = [

    # ── 1. _wire_screen_buttons(): Neue Helfer am Ende aufrufen ─────────────
    (
        "        # RBAUD dropdown — currentIndexChanged: send RB frame to TNC\n"
        "        if hasattr(screen, \"combo_rbaud\"):\n"
        "            try:\n"
        "                screen.combo_rbaud.currentIndexChanged.disconnect(\n"
        "                    self._on_screen_rbaud_changed\n"
        "                )\n"
        "            except RuntimeError:\n"
        "                pass\n"
        "            screen.combo_rbaud.currentIndexChanged.connect(\n"
        "                self._on_screen_rbaud_changed\n"
        "            )\n",

        "        # RBAUD dropdown — currentIndexChanged: send RB frame to TNC\n"
        "        if hasattr(screen, \"combo_rbaud\"):\n"
        "            try:\n"
        "                screen.combo_rbaud.currentIndexChanged.disconnect(\n"
        "                    self._on_screen_rbaud_changed\n"
        "                )\n"
        "            except RuntimeError:\n"
        "                pass\n"
        "            screen.combo_rbaud.currentIndexChanged.connect(\n"
        "                self._on_screen_rbaud_changed\n"
        "            )\n"
        "\n"
        "        # Phase 3 — identity fields, spinboxes, toggles, NAVTEX filters\n"
        "        self._wire_identity_fields(screen)\n"
        "        self._wire_morse_params(screen)\n"
        "        self._wire_toggle_buttons(screen)\n"
        "        self._wire_navtex_filters(screen)\n"
    ),

    # ── 2. Neue Methoden vor _on_mode_data_received() einfügen ───────────────
    (
        "    def _on_mode_data_received(self, data: bytes) -> None:\n"
        "        \"\"\"Display decoded data from active mode in RX panel.\"\"\"",

        # ── _wire_identity_fields ────────────────────────────────────────────
        "    def _wire_identity_fields(self, screen) -> None:\n"
        "        \"\"\"Wire identity QLineEdit fields to TNC parameter frames.\n"
        "\n"
        "        Covers:\n"
        "          PACTOR  le_myptcall  → PACTORMode.myptcall_frame()  (MK)\n"
        "          AMTOR   le_myselcal  → AMTORMode.myselcal_frame()   (MG)\n"
        "          AMTOR   le_myaltcal  → AMTORMode.myaltcal_frame()   (MK)\n"
        "          AMTOR   le_myident   → AMTORMode.myident_frame()    (MY)\n"
        "\n"
        "        Uses editingFinished so the frame is only sent when the\n"
        "        user leaves the field (Enter or focus-out), not on every\n"
        "        keystroke.\n"
        "        \"\"\"\n"
        "        def _wire(field_name: str, slot) -> None:\n"
        "            field = getattr(screen, field_name, None)\n"
        "            if field is None:\n"
        "                return\n"
        "            try:\n"
        "                field.editingFinished.disconnect(slot)\n"
        "            except RuntimeError:\n"
        "                pass\n"
        "            field.editingFinished.connect(slot)\n"
        "\n"
        "        _wire(\"le_myptcall\",  self._on_pactor_myptcall_changed)\n"
        "        _wire(\"le_myselcal\",  self._on_amtor_myselcal_changed)\n"
        "        _wire(\"le_myaltcal\",  self._on_amtor_myaltcal_changed)\n"
        "        _wire(\"le_myident\",   self._on_amtor_myident_changed)\n"
        "\n"
        "    def _on_pactor_myptcall_changed(self) -> None:\n"
        "        \"\"\"Send MYPTCALL frame when le_myptcall editingFinished fires.\"\"\"\n"
        "        if not self._serial.is_connected:\n"
        "            return\n"
        "        screen = self._opmode_stack.currentWidget()\n"
        "        call = getattr(screen, \"le_myptcall\", None)\n"
        "        if call is None:\n"
        "            return\n"
        "        text = call.text().strip().upper()\n"
        "        if not text:\n"
        "            return\n"
        "        from pk232py.modes.pactor import PACTORMode\n"
        "        frame = PACTORMode.myptcall_frame(text)\n"
        "        self._serial.send_command(frame[2:4], frame[4:-1])\n"
        "        # Keep mode instance in sync\n"
        "        mode = self._modes.current_mode\n"
        "        if hasattr(mode, \"myptcall\"):\n"
        "            mode.myptcall = text\n"
        "        self._log_monitor(f\"[PARAM] MYPTCALL → {text}\")\n"
        "\n"
        "    def _on_amtor_myselcal_changed(self) -> None:\n"
        "        \"\"\"Send MYSELCAL frame when le_myselcal editingFinished fires.\"\"\"\n"
        "        if not self._serial.is_connected or not self._serial.is_host_mode:\n"
        "            return\n"
        "        screen = self._opmode_stack.currentWidget()\n"
        "        field = getattr(screen, \"le_myselcal\", None)\n"
        "        if field is None:\n"
        "            return\n"
        "        text = field.text().strip().upper()\n"
        "        if not text:\n"
        "            return\n"
        "        from pk232py.modes.amtor import AMTORMode\n"
        "        frame = AMTORMode.myselcal_frame(text)\n"
        "        self._serial.send_command(frame[2:4], frame[4:-1])\n"
        "        mode = self._modes.current_mode\n"
        "        if hasattr(mode, \"myselcal\"):\n"
        "            mode.myselcal = text\n"
        "        self._log_monitor(f\"[PARAM] MYSELCAL → {text}\")\n"
        "\n"
        "    def _on_amtor_myaltcal_changed(self) -> None:\n"
        "        \"\"\"Send MYALTCAL frame when le_myaltcal editingFinished fires.\"\"\"\n"
        "        if not self._serial.is_connected or not self._serial.is_host_mode:\n"
        "            return\n"
        "        screen = self._opmode_stack.currentWidget()\n"
        "        field = getattr(screen, \"le_myaltcal\", None)\n"
        "        if field is None:\n"
        "            return\n"
        "        text = field.text().strip().upper()\n"
        "        from pk232py.modes.amtor import AMTORMode\n"
        "        frame = AMTORMode.myaltcal_frame(text)\n"
        "        self._serial.send_command(frame[2:4], frame[4:-1])\n"
        "        mode = self._modes.current_mode\n"
        "        if hasattr(mode, \"myaltcal\"):\n"
        "            mode.myaltcal = text\n"
        "        self._log_monitor(f\"[PARAM] MYALTCAL → {text or '(cleared)'}\")\n"
        "\n"
        "    def _on_amtor_myident_changed(self) -> None:\n"
        "        \"\"\"Send MYIDENT frame when le_myident editingFinished fires.\"\"\"\n"
        "        if not self._serial.is_connected or not self._serial.is_host_mode:\n"
        "            return\n"
        "        screen = self._opmode_stack.currentWidget()\n"
        "        field = getattr(screen, \"le_myident\", None)\n"
        "        if field is None:\n"
        "            return\n"
        "        text = field.text().strip().upper()\n"
        "        from pk232py.modes.amtor import AMTORMode\n"
        "        frame = AMTORMode.myident_frame(text)\n"
        "        self._serial.send_command(frame[2:4], frame[4:-1])\n"
        "        mode = self._modes.current_mode\n"
        "        if hasattr(mode, \"myident\"):\n"
        "            mode.myident = text\n"
        "        self._log_monitor(f\"[PARAM] MYIDENT → {text or '(cleared)'}\")\n"
        "\n"
        "    # ------------------------------------------------------------------\n"
        "    # Morse parameter wiring\n"
        "    # ------------------------------------------------------------------\n"
        "\n"
        "    def _wire_morse_params(self, screen) -> None:\n"
        "        \"\"\"Wire Morse SpinBoxes and LOCK button to TNC commands.\"\"\"\n"
        "\n"
        "        def _wire_sb(attr: str, slot) -> None:\n"
        "            sb = getattr(screen, attr, None)\n"
        "            if sb is None:\n"
        "                return\n"
        "            try:\n"
        "                sb.valueChanged.disconnect(slot)\n"
        "            except RuntimeError:\n"
        "                pass\n"
        "            sb.valueChanged.connect(slot)\n"
        "\n"
        "        def _wire_btn(attr: str, slot) -> None:\n"
        "            btn = getattr(screen, attr, None)\n"
        "            if btn is None:\n"
        "                return\n"
        "            try:\n"
        "                btn.clicked.disconnect(slot)\n"
        "            except RuntimeError:\n"
        "                pass\n"
        "            btn.clicked.connect(slot)\n"
        "\n"
        "        _wire_sb(\"sb_mspeed\",  self._on_morse_mspeed_changed)\n"
        "        _wire_sb(\"sb_mweight\", self._on_morse_mweight_changed)\n"
        "        _wire_sb(\"sb_mid\",     self._on_morse_mid_changed)\n"
        "        _wire_btn(\"btn_lock\",  self._on_morse_lock)\n"
        "\n"
        "    def _morse_send(self, frame: bytes) -> bool:\n"
        "        \"\"\"Send a Morse parameter frame. Guard: Host Mode required.\"\"\"\n"
        "        if not self._serial.is_connected or not self._serial.is_host_mode:\n"
        "            return False\n"
        "        return self._serial.send_command(frame[2:4], frame[4:-1])\n"
        "\n"
        "    def _on_morse_mspeed_changed(self, value: int) -> None:\n"
        "        \"\"\"MSPEED spinbox changed — send MP frame (mnemonic MP).\"\"\"\n"
        "        from pk232py.modes.morse import MorseMode\n"
        "        frame = MorseMode.mspeed_frame(value)\n"
        "        if self._morse_send(frame):\n"
        "            mode = self._modes.current_mode\n"
        "            if hasattr(mode, \"mspeed\"):\n"
        "                mode.mspeed = value\n"
        "            self._log_monitor(f\"[PARAM] MSPEED → {value} WPM\")\n"
        "\n"
        "    def _on_morse_mweight_changed(self, value: int) -> None:\n"
        "        \"\"\"MWEIGHT spinbox changed — send MW frame (mnemonic MW).\"\"\"\n"
        "        from pk232py.modes.morse import MorseMode\n"
        "        frame = MorseMode.mweight_frame(value)\n"
        "        if self._morse_send(frame):\n"
        "            mode = self._modes.current_mode\n"
        "            if hasattr(mode, \"mweight\"):\n"
        "                mode.mweight = value\n"
        "            self._log_monitor(f\"[PARAM] MWEIGHT → {value}\")\n"
        "\n"
        "    def _on_morse_mid_changed(self, value: int) -> None:\n"
        "        \"\"\"MID spinbox changed — send MI frame (mnemonic MI).\"\"\"\n"
        "        from pk232py.modes.morse import MorseMode\n"
        "        frame = MorseMode.mid_frame(value)\n"
        "        if self._morse_send(frame):\n"
        "            mode = self._modes.current_mode\n"
        "            if hasattr(mode, \"mid\"):\n"
        "                mode.mid = value\n"
        "            self._log_monitor(f\"[PARAM] MID → {value} min\")\n"
        "\n"
        "    def _on_morse_lock(self) -> None:\n"
        "        \"\"\"LOCK button — lock RX speed to current signal (mnemonic LO).\"\"\"\n"
        "        from pk232py.modes.morse import MorseMode\n"
        "        frame = MorseMode.lock_frame()\n"
        "        if self._morse_send(frame):\n"
        "            self._log_monitor(\"[MORSE] LOCK — RX speed locked to signal\")\n"
        "\n"
        "    # ------------------------------------------------------------------\n"
        "    # Toggle button wiring (RXREV, TXREV, EAS, WIDESHFT, PT200, …)\n"
        "    # ------------------------------------------------------------------\n"
        "\n"
        "    def _wire_toggle_buttons(self, screen) -> None:\n"
        "        \"\"\"Wire all toggle buttons on the active screen to TNC frames.\n"
        "\n"
        "        Each entry: (widget_attr, mode_class_path, frame_method_name, instance_attr)\n"
        "        The slot is built dynamically from these components.\n"
        "        \"\"\"\n"
        "        mode = self._modes.current_mode\n"
        "        if mode is None:\n"
        "            return\n"
        "\n"
        "        # Map: btn_attr → (frame_builder_callable, instance_attr_name)\n"
        "        # frame_builder takes a bool and returns bytes\n"
        "        from pk232py.modes.amtor   import AMTORMode\n"
        "        from pk232py.modes.morse   import MorseMode\n"
        "        from pk232py.modes.pactor  import PACTORMode\n"
        "        from pk232py.modes.rtty_baudot import BaudotRTTYMode\n"
        "        from pk232py.modes.rtty_ascii  import ASCIIRTTYMode\n"
        "\n"
        "        toggle_map = {\n"
        "            # AMTOR toggles\n"
        "            \"btn_rxrev\":    (AMTORMode.rxrev_frame,   \"rxrev\"),\n"
        "            \"btn_txrev\":    (AMTORMode.txrev_frame,   \"txrev\"),\n"
        "            \"btn_rfec\":     (AMTORMode.rfec_frame,    \"rfec\"),\n"
        "            \"btn_srxall\":   (AMTORMode.srxall_frame,  \"srxall\"),\n"
        "            \"btn_eas\":      (AMTORMode.eas_frame,     \"eas\"),\n"
        "            # Morse toggles (share same attr names, same mnemonic pattern)\n"
        "            \"btn_wordout\":  (MorseMode.wordout_frame, \"wordout\"),\n"
        "            \"btn_moptt\":    (None,                    None),   # MO toggle — handled separately\n"
        "            # PACTOR toggles\n"
        "            \"btn_pt200\":    (PACTORMode.pt200_frame,  None),\n"
        "            \"btn_pthuff\":   (PACTORMode.pthuff_frame, None),\n"
        "            \"btn_ptround\":  (PACTORMode.ptround_frame, None),\n"
        "            # Baudot/ASCII toggles\n"
        "            \"btn_wideshft\": (BaudotRTTYMode.wideshft_frame, \"wideshft\"),\n"
        "        }\n"
        "\n"
        "        for btn_name, (frame_fn, inst_attr) in toggle_map.items():\n"
        "            btn = getattr(screen, btn_name, None)\n"
        "            if btn is None or frame_fn is None:\n"
        "                continue\n"
        "            # Build a closure capturing frame_fn and inst_attr\n"
        "            def _make_slot(fn, attr):\n"
        "                def slot(checked: bool) -> None:\n"
        "                    if not self._serial.is_connected or not self._serial.is_host_mode:\n"
        "                        return\n"
        "                    frame = fn(checked)\n"
        "                    self._serial.send_command(frame[2:4], frame[4:-1])\n"
        "                    if attr:\n"
        "                        m = self._modes.current_mode\n"
        "                        if m and hasattr(m, attr):\n"
        "                            setattr(m, attr, checked)\n"
        "                    self._log_monitor(\n"
        "                        f\"[PARAM] {btn_name.replace('btn_', '').upper()}\"\n"
        "                        f\" → {'ON' if checked else 'OFF'}\"\n"
        "                    )\n"
        "                return slot\n"
        "            try:\n"
        "                btn.toggled.disconnect()\n"
        "            except RuntimeError:\n"
        "                pass\n"
        "            # Reconnect screen-internal slot first (visual only)\n"
        "            # then the TNC slot\n"
        "            btn.toggled.connect(_make_slot(frame_fn, inst_attr))\n"
        "\n"
        "    # ------------------------------------------------------------------\n"
        "    # NAVTEX filter wiring\n"
        "    # ------------------------------------------------------------------\n"
        "\n"
        "    def _wire_navtex_filters(self, screen) -> None:\n"
        "        \"\"\"Wire NAVTEX NAVMSG checkboxes and NAVSTN field to TNC.\"\"\"\n"
        "        # NAVMSG checkboxes — stateChanged\n"
        "        msg_checks = getattr(screen, \"_msg_checks\", None)\n"
        "        if msg_checks is not None:\n"
        "            for letter, cb in msg_checks.items():\n"
        "                try:\n"
        "                    cb.stateChanged.disconnect(self._on_navtex_navmsg_changed)\n"
        "                except RuntimeError:\n"
        "                    pass\n"
        "                cb.stateChanged.connect(self._on_navtex_navmsg_changed)\n"
        "\n"
        "        # NAVSTN field — editingFinished\n"
        "        le_navstn = getattr(screen, \"le_navstn\", None)\n"
        "        if le_navstn is not None:\n"
        "            try:\n"
        "                le_navstn.editingFinished.disconnect(\n"
        "                    self._on_navtex_navstn_changed\n"
        "                )\n"
        "            except RuntimeError:\n"
        "                pass\n"
        "            le_navstn.editingFinished.connect(\n"
        "                self._on_navtex_navstn_changed\n"
        "            )\n"
        "\n"
        "    def _on_navtex_navmsg_changed(self) -> None:\n"
        "        \"\"\"Any NAVMSG checkbox changed — rebuild filter and send NM frame.\"\"\"\n"
        "        if not self._serial.is_connected or not self._serial.is_host_mode:\n"
        "            return\n"
        "        screen = self._opmode_stack.currentWidget()\n"
        "        if not hasattr(screen, \"get_navmsg_filter\"):\n"
        "            return\n"
        "        filter_str = screen.get_navmsg_filter()\n"
        "        from pk232py.modes.navtex import NAVTEXMode\n"
        "        frame = NAVTEXMode.navmsg_frame(filter_str)\n"
        "        self._serial.send_command(frame[2:4], frame[4:-1])\n"
        "        mode = self._modes.current_mode\n"
        "        if hasattr(mode, \"navmsg\"):\n"
        "            mode.navmsg = filter_str\n"
        "        self._log_monitor(f\"[PARAM] NAVMSG → {filter_str}\")\n"
        "\n"
        "    def _on_navtex_navstn_changed(self) -> None:\n"
        "        \"\"\"NAVSTN field editingFinished — send NS frame.\"\"\"\n"
        "        if not self._serial.is_connected or not self._serial.is_host_mode:\n"
        "            return\n"
        "        screen = self._opmode_stack.currentWidget()\n"
        "        if not hasattr(screen, \"get_navstn_filter\"):\n"
        "            return\n"
        "        filter_str = screen.get_navstn_filter()\n"
        "        from pk232py.modes.navtex import NAVTEXMode\n"
        "        frame = NAVTEXMode.navstn_frame(filter_str)\n"
        "        self._serial.send_command(frame[2:4], frame[4:-1])\n"
        "        mode = self._modes.current_mode\n"
        "        if hasattr(mode, \"navstn\"):\n"
        "            mode.navstn = filter_str\n"
        "        self._log_monitor(f\"[PARAM] NAVSTN → {filter_str}\")\n"
        "\n"
        "    def _on_mode_data_received(self, data: bytes) -> None:\n"
        "        \"\"\"Display decoded data from active mode in RX panel.\"\"\""
    ),

]


def apply_patches(path: Path, patches: list[tuple]) -> None:
    src = path.read_text(encoding="utf-8")

    missing = []
    for i, patch in enumerate(patches, 1):
        if patch[0] not in src:
            missing.append(i)

    if missing:
        print(f"FEHLER: Suchstring nicht gefunden fuer Patch(e): {missing}")
        print("Patch wird NICHT angewendet — Datei unveraendert.")
        return

    for i, patch in enumerate(patches, 1):
        src = src.replace(patch[0], patch[1], 1)
        print(f"OK  Patch {i} angewendet")

    path.write_text(src, encoding="utf-8")
    print(f"\nFertig — {path} aktualisiert.")


if __name__ == "__main__":
    if not TARGET.exists():
        print(f"Datei nicht gefunden: {TARGET}")
    else:
        apply_patches(TARGET, PATCHES)